#spring:
  #datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/studs
    #username:
    #password:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/blps_3}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.yandex.ru
    username: yulikamaltseva@yandex.ru
    port: 465
    protocol: smtps
    debug: true
    password:
  kafka:
    consumer:
      group-id: consumergroup${random.value}
    bootstrap-servers: localhost:9092


# Настройки для профиля "master"
---
spring:
  config:
    activate:
      on-profile: master
server:
  port: 17502

# Настройки для профиля "slave"
---
spring:
  config:
    activate:
      on-profile: slave
server:
  port: 17503
