#spring:
  #datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/studs
    #username: s311685
    #password: Qke0HDlQuiOJ0FYk

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blps2
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.yandex.ru
    username: yulikamaltseva@yandex.ru
    port: 465
    protocol: smtps
    debug: true
    password:
  kafka:
    consumer:
      group-id: consumergroup${random.value}

spring.kafka.bootstrap-servers: localhost:9092


# Настройки для профиля "master"
---
spring:
  config:
    activate:
      on-profile: master
server:
  port: 17502

# Настройки для профиля "slave"
---
spring:
  config:
    activate:
      on-profile: slave
server:
  port: 17503