#spring:
  #datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/studs
    #username: s311685
    #password: Qke0HDlQuiOJ0FYk

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blps2
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9443