package com.nullnumber1.lab1.util.enums;

public enum Code {
  RESOURCE_NOT_FOUND,
  NOT_MATCHES,
  IMPOSSIBLE_OPERATION,
  INTERNAL_SERVER_ERROR,
  JSON_ERROR,
  UNSUPPORTED_MEDIA_TYPE,
  AUTH_ERROR,
  TRANSACTION_ERROR,
  BAD_REQUEST,
  DOCUMENT_ERROR
}
